
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.zachsedit.lifealikes.init;

import net.zachsedit.lifealikes.block.WhiteschistBlock;
import net.zachsedit.lifealikes.block.WehrliteBlock;
import net.zachsedit.lifealikes.block.WebsteriteBlock;
import net.zachsedit.lifealikes.block.WadBlock;
import net.zachsedit.lifealikes.block.WackestoneBlock;
import net.zachsedit.lifealikes.block.VertisolBlock;
import net.zachsedit.lifealikes.block.VarioliteBlock;
import net.zachsedit.lifealikes.block.UnakiteBlock;
import net.zachsedit.lifealikes.block.UltisolsBlock;
import net.zachsedit.lifealikes.block.TurbiditeBlock;
import net.zachsedit.lifealikes.block.TuffBlock;
import net.zachsedit.lifealikes.block.TufaBlock;
import net.zachsedit.lifealikes.block.TrondhjemiteBlock;
import net.zachsedit.lifealikes.block.TroctoliteBlock;
import net.zachsedit.lifealikes.block.TravertineBlock;
import net.zachsedit.lifealikes.block.TrachyteBlock;
import net.zachsedit.lifealikes.block.TrachybasaltBlock;
import net.zachsedit.lifealikes.block.TrachyandesiteBlock;
import net.zachsedit.lifealikes.block.TonaliteBlock;
import net.zachsedit.lifealikes.block.TilliteBlock;
import net.zachsedit.lifealikes.block.TheraliteBlock;
import net.zachsedit.lifealikes.block.TescheniteBlock;
import net.zachsedit.lifealikes.block.TephriteBlock;
import net.zachsedit.lifealikes.block.TephriphonoliteBlock;
import net.zachsedit.lifealikes.block.TectoniteBlock;
import net.zachsedit.lifealikes.block.TaconiteBlock;
import net.zachsedit.lifealikes.block.TachylyteBlock;
import net.zachsedit.lifealikes.block.TachyliteBlock;
import net.zachsedit.lifealikes.block.SylviniteBlock;
import net.zachsedit.lifealikes.block.SyeniteBlock;
import net.zachsedit.lifealikes.block.SueviteBlock;
import net.zachsedit.lifealikes.block.StagnosolsBlock;
import net.zachsedit.lifealikes.block.SpodosolsBlock;
import net.zachsedit.lifealikes.block.SoviteBlock;
import net.zachsedit.lifealikes.block.SolonetzBlock;
import net.zachsedit.lifealikes.block.SolonchaksBlock;
import net.zachsedit.lifealikes.block.SoapstoneBlock;
import net.zachsedit.lifealikes.block.SlateBlock;
import net.zachsedit.lifealikes.block.SkarnBlock;
import net.zachsedit.lifealikes.block.SiltstoneBlock;
import net.zachsedit.lifealikes.block.ShoshoniteBlock;
import net.zachsedit.lifealikes.block.ShonkiniteBlock;
import net.zachsedit.lifealikes.block.ShaleBlock;
import net.zachsedit.lifealikes.block.SerpentiniteBlock;
import net.zachsedit.lifealikes.block.ScoriaBlock;
import net.zachsedit.lifealikes.block.SchistBlock;
import net.zachsedit.lifealikes.block.SandstoneBlock;
import net.zachsedit.lifealikes.block.RodingiteBlock;
import net.zachsedit.lifealikes.block.RhyoliteBlock;
import net.zachsedit.lifealikes.block.RhyodaciteBlock;
import net.zachsedit.lifealikes.block.RendzinasBlock;
import net.zachsedit.lifealikes.block.RegosolsBlock;
import net.zachsedit.lifealikes.block.QuartzoliteBlock;
import net.zachsedit.lifealikes.block.QuartziteBlock;
import net.zachsedit.lifealikes.block.PyroxeniteBlock;
import net.zachsedit.lifealikes.block.PyroliteBlock;
import net.zachsedit.lifealikes.block.PumiceBlock;
import net.zachsedit.lifealikes.block.PseudotachyliteBlock;
import net.zachsedit.lifealikes.block.PorphyryBlock;
import net.zachsedit.lifealikes.block.PodosolsBlock;
import net.zachsedit.lifealikes.block.PlinthosolsBlock;
import net.zachsedit.lifealikes.block.PlanosolsBlock;
import net.zachsedit.lifealikes.block.PietersiteBlock;
import net.zachsedit.lifealikes.block.PicriteBlock;
import net.zachsedit.lifealikes.block.PhylliteBlock;
import net.zachsedit.lifealikes.block.PhosphoriteBlock;
import net.zachsedit.lifealikes.block.PhonotephriteBlock;
import net.zachsedit.lifealikes.block.PhonoliteBlock;
import net.zachsedit.lifealikes.block.PeridotiteBlock;
import net.zachsedit.lifealikes.block.PelisolsBlock;
import net.zachsedit.lifealikes.block.PegmatiteBlock;
import net.zachsedit.lifealikes.block.PantelleriteBlock;
import net.zachsedit.lifealikes.block.OxisolsBlock;
import net.zachsedit.lifealikes.block.OoliteBlock;
import net.zachsedit.lifealikes.block.NovaculiteBlock;
import net.zachsedit.lifealikes.block.NoriteBlock;
import net.zachsedit.lifealikes.block.NitisolsBlock;
import net.zachsedit.lifealikes.block.NepheliniteBlock;
import net.zachsedit.lifealikes.block.NapoleoniteBlock;
import net.zachsedit.lifealikes.block.MyloniteBlock;
import net.zachsedit.lifealikes.block.MugeariteBlock;
import net.zachsedit.lifealikes.block.MudstoneBlock;
import net.zachsedit.lifealikes.block.MonzoniteBlock;
import net.zachsedit.lifealikes.block.MonzograniteBlock;
import net.zachsedit.lifealikes.block.MollisolsBlock;
import net.zachsedit.lifealikes.block.MigmatiteBlock;
import net.zachsedit.lifealikes.block.MetapsammiteBlock;
import net.zachsedit.lifealikes.block.MetapeliteBlock;
import net.zachsedit.lifealikes.block.MarlBlock;
import net.zachsedit.lifealikes.block.MarbleBlock;
import net.zachsedit.lifealikes.block.MangeriteBlock;
import net.zachsedit.lifealikes.block.LuxullianiteBlock;
import net.zachsedit.lifealikes.block.LuvisolsBlock;
import net.zachsedit.lifealikes.block.LlaniteBlock;
import net.zachsedit.lifealikes.block.LixisolsBlock;
import net.zachsedit.lifealikes.block.LithosolsBlock;
import net.zachsedit.lifealikes.block.LitchfielditeBlock;
import net.zachsedit.lifealikes.block.LimestoneBlock;
import net.zachsedit.lifealikes.block.LigniteBlock;
import net.zachsedit.lifealikes.block.LherzoliteBlock;
import net.zachsedit.lifealikes.block.LeptosolsBlock;
import net.zachsedit.lifealikes.block.LatiteBlock;
import net.zachsedit.lifealikes.block.LateriteBlock;
import net.zachsedit.lifealikes.block.LarvikiteBlock;
import net.zachsedit.lifealikes.block.LamprophyreBlock;
import net.zachsedit.lifealikes.block.LamproiteBlock;
import net.zachsedit.lifealikes.block.KomatiiteBlock;
import net.zachsedit.lifealikes.block.KimberliteBlock;
import net.zachsedit.lifealikes.block.KenyteBlock;
import net.zachsedit.lifealikes.block.JaspilliteBlock;
import net.zachsedit.lifealikes.block.JasperoidBlock;
import net.zachsedit.lifealikes.block.JadeititeBlock;
import net.zachsedit.lifealikes.block.ItacolumiteBlock;
import net.zachsedit.lifealikes.block.InceptisolsBlock;
import net.zachsedit.lifealikes.block.IjoliteBlock;
import net.zachsedit.lifealikes.block.IgnimbriteBlock;
import net.zachsedit.lifealikes.block.IcelanditeBlock;
import net.zachsedit.lifealikes.block.HyaloclastiteBlock;
import net.zachsedit.lifealikes.block.HornfelsBlock;
import net.zachsedit.lifealikes.block.HornblenditeBlock;
import net.zachsedit.lifealikes.block.HistosolsBlock;
import net.zachsedit.lifealikes.block.HistosolBlock;
import net.zachsedit.lifealikes.block.HawaiiteBlock;
import net.zachsedit.lifealikes.block.HarzburgiteBlock;
import net.zachsedit.lifealikes.block.GritstoneBlock;
import net.zachsedit.lifealikes.block.GreywackeBlock;
import net.zachsedit.lifealikes.block.GreenschistBlock;
import net.zachsedit.lifealikes.block.GranuliteBlock;
import net.zachsedit.lifealikes.block.GranophyreBlock;
import net.zachsedit.lifealikes.block.GranodioriteBlock;
import net.zachsedit.lifealikes.block.GossanBlock;
import net.zachsedit.lifealikes.block.GneissBlock;
import net.zachsedit.lifealikes.block.GleysolBlock;
import net.zachsedit.lifealikes.block.GeyseriteBlock;
import net.zachsedit.lifealikes.block.GelisolsBlock;
import net.zachsedit.lifealikes.block.GanisterBlock;
import net.zachsedit.lifealikes.block.GabbroBlock;
import net.zachsedit.lifealikes.block.FoidoliteBlock;
import net.zachsedit.lifealikes.block.FluvisolsBlock;
import net.zachsedit.lifealikes.block.FlintBlock;
import net.zachsedit.lifealikes.block.FerralsolsBlock;
import net.zachsedit.lifealikes.block.FelsiteBlock;
import net.zachsedit.lifealikes.block.EvaporiteBlock;
import net.zachsedit.lifealikes.block.EssexiteBlock;
import net.zachsedit.lifealikes.block.EpidositeBlock;
import net.zachsedit.lifealikes.block.EntisolsBlock;
import net.zachsedit.lifealikes.block.EnderbiteBlock;
import net.zachsedit.lifealikes.block.EclogiteBlock;
import net.zachsedit.lifealikes.block.DurisolsBlock;
import net.zachsedit.lifealikes.block.DuniteBlock;
import net.zachsedit.lifealikes.block.DolomiteBlock;
import net.zachsedit.lifealikes.block.DioriteBlock;
import net.zachsedit.lifealikes.block.DiatomiteBlock;
import net.zachsedit.lifealikes.block.DiamictiteBlock;
import net.zachsedit.lifealikes.block.DiabaseBlock;
import net.zachsedit.lifealikes.block.DaciteBlock;
import net.zachsedit.lifealikes.block.CryosolsBlock;
import net.zachsedit.lifealikes.block.CoquinaBlock;
import net.zachsedit.lifealikes.block.ConglomerateBlock;
import net.zachsedit.lifealikes.block.ComenditeBlock;
import net.zachsedit.lifealikes.block.CoalBlock;
import net.zachsedit.lifealikes.block.ClaystoneBlock;
import net.zachsedit.lifealikes.block.ChertBlock;
import net.zachsedit.lifealikes.block.ChernozemsBlock;
import net.zachsedit.lifealikes.block.CharnockiteBlock;
import net.zachsedit.lifealikes.block.ChalkBlock;
import net.zachsedit.lifealikes.block.CataclasiteBlock;
import net.zachsedit.lifealikes.block.CarbonatiteBlock;
import net.zachsedit.lifealikes.block.CambisolsBlock;
import net.zachsedit.lifealikes.block.CalcisolsBlock;
import net.zachsedit.lifealikes.block.CalcflintaBlock;
import net.zachsedit.lifealikes.block.CalcareniteBlock;
import net.zachsedit.lifealikes.block.BrecciaBlock;
import net.zachsedit.lifealikes.block.BorolaniteBlock;
import net.zachsedit.lifealikes.block.BoniniteBlock;
import net.zachsedit.lifealikes.block.BlueschistBlock;
import net.zachsedit.lifealikes.block.BlairmoriteBlock;
import net.zachsedit.lifealikes.block.BenmoreiteBlock;
import net.zachsedit.lifealikes.block.BasaniteBlock;
import net.zachsedit.lifealikes.block.ArkoseBlock;
import net.zachsedit.lifealikes.block.AridisolsBlock;
import net.zachsedit.lifealikes.block.ArgilliteBlock;
import net.zachsedit.lifealikes.block.ArenosolsBlock;
import net.zachsedit.lifealikes.block.AppiniteBlock;
import net.zachsedit.lifealikes.block.AphaniteBlock;
import net.zachsedit.lifealikes.block.AnthraciteBlock;
import net.zachsedit.lifealikes.block.AndisolBlock;
import net.zachsedit.lifealikes.block.AmphiboliteBlock;
import net.zachsedit.lifealikes.block.AlfisolsBlock;
import net.zachsedit.lifealikes.block.AlbeluvisolsBlock;
import net.zachsedit.lifealikes.block.AdamelliteBlock;
import net.zachsedit.lifealikes.block.AdakiteBlock;
import net.zachsedit.lifealikes.LifealikesMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

public class LifealikesModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, LifealikesMod.MODID);
	public static final RegistryObject<Block> ADAKITE = REGISTRY.register("adakite", () -> new AdakiteBlock());
	public static final RegistryObject<Block> VERTISOL = REGISTRY.register("vertisol", () -> new VertisolBlock());
	public static final RegistryObject<Block> ANDISOL = REGISTRY.register("andisol", () -> new AndisolBlock());
	public static final RegistryObject<Block> HISTOSOL = REGISTRY.register("histosol", () -> new HistosolBlock());
	public static final RegistryObject<Block> GLEYSOL = REGISTRY.register("gleysol", () -> new GleysolBlock());
	public static final RegistryObject<Block> ARIDISOLS = REGISTRY.register("aridisols", () -> new AridisolsBlock());
	public static final RegistryObject<Block> MOLLISOLS = REGISTRY.register("mollisols", () -> new MollisolsBlock());
	public static final RegistryObject<Block> ALFISOLS = REGISTRY.register("alfisols", () -> new AlfisolsBlock());
	public static final RegistryObject<Block> SPODOSOLS = REGISTRY.register("spodosols", () -> new SpodosolsBlock());
	public static final RegistryObject<Block> INCEPTISOLS = REGISTRY.register("inceptisols", () -> new InceptisolsBlock());
	public static final RegistryObject<Block> ENTISOLS = REGISTRY.register("entisols", () -> new EntisolsBlock());
	public static final RegistryObject<Block> OXISOLS = REGISTRY.register("oxisols", () -> new OxisolsBlock());
	public static final RegistryObject<Block> ULTISOLS = REGISTRY.register("ultisols", () -> new UltisolsBlock());
	public static final RegistryObject<Block> GELISOLS = REGISTRY.register("gelisols", () -> new GelisolsBlock());
	public static final RegistryObject<Block> PODOSOLS = REGISTRY.register("podosols", () -> new PodosolsBlock());
	public static final RegistryObject<Block> LUVISOLS = REGISTRY.register("luvisols", () -> new LuvisolsBlock());
	public static final RegistryObject<Block> CHERNOZEMS = REGISTRY.register("chernozems", () -> new ChernozemsBlock());
	public static final RegistryObject<Block> FERRALSOLS = REGISTRY.register("ferralsols", () -> new FerralsolsBlock());
	public static final RegistryObject<Block> NITISOLS = REGISTRY.register("nitisols", () -> new NitisolsBlock());
	public static final RegistryObject<Block> LEPTOSOLS = REGISTRY.register("leptosols", () -> new LeptosolsBlock());
	public static final RegistryObject<Block> REGOSOLS = REGISTRY.register("regosols", () -> new RegosolsBlock());
	public static final RegistryObject<Block> CALCISOLS = REGISTRY.register("calcisols", () -> new CalcisolsBlock());
	public static final RegistryObject<Block> LITHOSOLS = REGISTRY.register("lithosols", () -> new LithosolsBlock());
	public static final RegistryObject<Block> PLINTHOSOLS = REGISTRY.register("plinthosols", () -> new PlinthosolsBlock());
	public static final RegistryObject<Block> PLANOSOLS = REGISTRY.register("planosols", () -> new PlanosolsBlock());
	public static final RegistryObject<Block> CAMBISOLS = REGISTRY.register("cambisols", () -> new CambisolsBlock());
	public static final RegistryObject<Block> SOLONCHAKS = REGISTRY.register("solonchaks", () -> new SolonchaksBlock());
	public static final RegistryObject<Block> SOLONETZ = REGISTRY.register("solonetz", () -> new SolonetzBlock());
	public static final RegistryObject<Block> MUGEARITE = REGISTRY.register("mugearite", () -> new MugeariteBlock());
	public static final RegistryObject<Block> SHOSHONITE = REGISTRY.register("shoshonite", () -> new ShoshoniteBlock());
	public static final RegistryObject<Block> BASANITE = REGISTRY.register("basanite", () -> new BasaniteBlock());
	public static final RegistryObject<Block> BLAIRMORITE = REGISTRY.register("blairmorite", () -> new BlairmoriteBlock());
	public static final RegistryObject<Block> BONINITE = REGISTRY.register("boninite", () -> new BoniniteBlock());
	public static final RegistryObject<Block> CARBONATITE = REGISTRY.register("carbonatite", () -> new CarbonatiteBlock());
	public static final RegistryObject<Block> CHARNOCKITE = REGISTRY.register("charnockite", () -> new CharnockiteBlock());
	public static final RegistryObject<Block> ENDERBITE = REGISTRY.register("enderbite", () -> new EnderbiteBlock());
	public static final RegistryObject<Block> DACITE = REGISTRY.register("dacite", () -> new DaciteBlock());
	public static final RegistryObject<Block> DIABASE = REGISTRY.register("diabase", () -> new DiabaseBlock());
	public static final RegistryObject<Block> DIORITE = REGISTRY.register("diorite", () -> new DioriteBlock());
	public static final RegistryObject<Block> NAPOLEONITE = REGISTRY.register("napoleonite", () -> new NapoleoniteBlock());
	public static final RegistryObject<Block> DUNITE = REGISTRY.register("dunite", () -> new DuniteBlock());
	public static final RegistryObject<Block> ESSEXITE = REGISTRY.register("essexite", () -> new EssexiteBlock());
	public static final RegistryObject<Block> FOIDOLITE = REGISTRY.register("foidolite", () -> new FoidoliteBlock());
	public static final RegistryObject<Block> GABBRO = REGISTRY.register("gabbro", () -> new GabbroBlock());
	public static final RegistryObject<Block> GRANODIORITE = REGISTRY.register("granodiorite", () -> new GranodioriteBlock());
	public static final RegistryObject<Block> GRANOPHYRE = REGISTRY.register("granophyre", () -> new GranophyreBlock());
	public static final RegistryObject<Block> HARZBURGITE = REGISTRY.register("harzburgite", () -> new HarzburgiteBlock());
	public static final RegistryObject<Block> HORNBLENDITE = REGISTRY.register("hornblendite", () -> new HornblenditeBlock());
	public static final RegistryObject<Block> HYALOCLASTITE = REGISTRY.register("hyaloclastite", () -> new HyaloclastiteBlock());
	public static final RegistryObject<Block> ICELANDITE = REGISTRY.register("icelandite", () -> new IcelanditeBlock());
	public static final RegistryObject<Block> IGNIMBRITE = REGISTRY.register("ignimbrite", () -> new IgnimbriteBlock());
	public static final RegistryObject<Block> IJOLITE = REGISTRY.register("ijolite", () -> new IjoliteBlock());
	public static final RegistryObject<Block> KIMBERLITE = REGISTRY.register("kimberlite", () -> new KimberliteBlock());
	public static final RegistryObject<Block> KOMATIITE = REGISTRY.register("komatiite", () -> new KomatiiteBlock());
	public static final RegistryObject<Block> LAMPROITE = REGISTRY.register("lamproite", () -> new LamproiteBlock());
	public static final RegistryObject<Block> LAMPROPHYRE = REGISTRY.register("lamprophyre", () -> new LamprophyreBlock());
	public static final RegistryObject<Block> LATITE = REGISTRY.register("latite", () -> new LatiteBlock());
	public static final RegistryObject<Block> LHERZOLITE = REGISTRY.register("lherzolite", () -> new LherzoliteBlock());
	public static final RegistryObject<Block> MONZOGRANITE = REGISTRY.register("monzogranite", () -> new MonzograniteBlock());
	public static final RegistryObject<Block> MONZONITE = REGISTRY.register("monzonite", () -> new MonzoniteBlock());
	public static final RegistryObject<Block> NEPHELINITE = REGISTRY.register("nephelinite", () -> new NepheliniteBlock());
	public static final RegistryObject<Block> NORITE = REGISTRY.register("norite", () -> new NoriteBlock());
	public static final RegistryObject<Block> PEGMATITE = REGISTRY.register("pegmatite", () -> new PegmatiteBlock());
	public static final RegistryObject<Block> PERIDOTITE = REGISTRY.register("peridotite", () -> new PeridotiteBlock());
	public static final RegistryObject<Block> PHONOLITE = REGISTRY.register("phonolite", () -> new PhonoliteBlock());
	public static final RegistryObject<Block> PHONOTEPHRITE = REGISTRY.register("phonotephrite", () -> new PhonotephriteBlock());
	public static final RegistryObject<Block> PICRITE = REGISTRY.register("picrite", () -> new PicriteBlock());
	public static final RegistryObject<Block> PORPHYRY = REGISTRY.register("porphyry", () -> new PorphyryBlock());
	public static final RegistryObject<Block> PUMICE = REGISTRY.register("pumice", () -> new PumiceBlock());
	public static final RegistryObject<Block> PYROXENITE = REGISTRY.register("pyroxenite", () -> new PyroxeniteBlock());
	public static final RegistryObject<Block> QUARTZOLITE = REGISTRY.register("quartzolite", () -> new QuartzoliteBlock());
	public static final RegistryObject<Block> RHYODACITE = REGISTRY.register("rhyodacite", () -> new RhyodaciteBlock());
	public static final RegistryObject<Block> RHYOLITE = REGISTRY.register("rhyolite", () -> new RhyoliteBlock());
	public static final RegistryObject<Block> COMENDITE = REGISTRY.register("comendite", () -> new ComenditeBlock());
	public static final RegistryObject<Block> PANTELLERITE = REGISTRY.register("pantellerite", () -> new PantelleriteBlock());
	public static final RegistryObject<Block> SCORIA = REGISTRY.register("scoria", () -> new ScoriaBlock());
	public static final RegistryObject<Block> SHONKINITE = REGISTRY.register("shonkinite", () -> new ShonkiniteBlock());
	public static final RegistryObject<Block> SOVITE = REGISTRY.register("sovite", () -> new SoviteBlock());
	public static final RegistryObject<Block> SYENITE = REGISTRY.register("syenite", () -> new SyeniteBlock());
	public static final RegistryObject<Block> TACHYLYTE = REGISTRY.register("tachylyte", () -> new TachylyteBlock());
	public static final RegistryObject<Block> TEPHRIPHONOLITE = REGISTRY.register("tephriphonolite", () -> new TephriphonoliteBlock());
	public static final RegistryObject<Block> TEPHRITE = REGISTRY.register("tephrite", () -> new TephriteBlock());
	public static final RegistryObject<Block> TONALITE = REGISTRY.register("tonalite", () -> new TonaliteBlock());
	public static final RegistryObject<Block> TRACHYANDESITE = REGISTRY.register("trachyandesite", () -> new TrachyandesiteBlock());
	public static final RegistryObject<Block> BENMOREITE = REGISTRY.register("benmoreite", () -> new BenmoreiteBlock());
	public static final RegistryObject<Block> TRACHYBASALT = REGISTRY.register("trachybasalt", () -> new TrachybasaltBlock());
	public static final RegistryObject<Block> HAWAIITE = REGISTRY.register("hawaiite", () -> new HawaiiteBlock());
	public static final RegistryObject<Block> TRACHYTE = REGISTRY.register("trachyte", () -> new TrachyteBlock());
	public static final RegistryObject<Block> TROCTOLITE = REGISTRY.register("troctolite", () -> new TroctoliteBlock());
	public static final RegistryObject<Block> TRONDHJEMITE = REGISTRY.register("trondhjemite", () -> new TrondhjemiteBlock());
	public static final RegistryObject<Block> TUFF = REGISTRY.register("tuff", () -> new TuffBlock());
	public static final RegistryObject<Block> WEBSTERITE = REGISTRY.register("websterite", () -> new WebsteriteBlock());
	public static final RegistryObject<Block> WEHRLITE = REGISTRY.register("wehrlite", () -> new WehrliteBlock());
	public static final RegistryObject<Block> ARGILLITE = REGISTRY.register("argillite", () -> new ArgilliteBlock());
	public static final RegistryObject<Block> ARKOSE = REGISTRY.register("arkose", () -> new ArkoseBlock());
	public static final RegistryObject<Block> BRECCIA = REGISTRY.register("breccia", () -> new BrecciaBlock());
	public static final RegistryObject<Block> CALCARENITE = REGISTRY.register("calcarenite", () -> new CalcareniteBlock());
	public static final RegistryObject<Block> CHALK = REGISTRY.register("chalk", () -> new ChalkBlock());
	public static final RegistryObject<Block> CHERT = REGISTRY.register("chert", () -> new ChertBlock());
	public static final RegistryObject<Block> CLAYSTONE = REGISTRY.register("claystone", () -> new ClaystoneBlock());
	public static final RegistryObject<Block> COAL = REGISTRY.register("coal", () -> new CoalBlock());
	public static final RegistryObject<Block> CONGLOMERATE = REGISTRY.register("conglomerate", () -> new ConglomerateBlock());
	public static final RegistryObject<Block> COQUINA = REGISTRY.register("coquina", () -> new CoquinaBlock());
	public static final RegistryObject<Block> DIAMICTITE = REGISTRY.register("diamictite", () -> new DiamictiteBlock());
	public static final RegistryObject<Block> DIATOMITE = REGISTRY.register("diatomite", () -> new DiatomiteBlock());
	public static final RegistryObject<Block> DOLOMITE = REGISTRY.register("dolomite", () -> new DolomiteBlock());
	public static final RegistryObject<Block> EVAPORITE = REGISTRY.register("evaporite", () -> new EvaporiteBlock());
	public static final RegistryObject<Block> FLINT = REGISTRY.register("flint", () -> new FlintBlock());
	public static final RegistryObject<Block> GEYSERITE = REGISTRY.register("geyserite", () -> new GeyseriteBlock());
	public static final RegistryObject<Block> GREYWACKE = REGISTRY.register("greywacke", () -> new GreywackeBlock());
	public static final RegistryObject<Block> GRITSTONE = REGISTRY.register("gritstone", () -> new GritstoneBlock());
	public static final RegistryObject<Block> ITACOLUMITE = REGISTRY.register("itacolumite", () -> new ItacolumiteBlock());
	public static final RegistryObject<Block> JASPILLITE = REGISTRY.register("jaspillite", () -> new JaspilliteBlock());
	public static final RegistryObject<Block> LATERITE = REGISTRY.register("laterite", () -> new LateriteBlock());
	public static final RegistryObject<Block> LIGNITE = REGISTRY.register("lignite", () -> new LigniteBlock());
	public static final RegistryObject<Block> LIMESTONE = REGISTRY.register("limestone", () -> new LimestoneBlock());
	public static final RegistryObject<Block> MARL = REGISTRY.register("marl", () -> new MarlBlock());
	public static final RegistryObject<Block> MUDSTONE = REGISTRY.register("mudstone", () -> new MudstoneBlock());
	public static final RegistryObject<Block> OOLITE = REGISTRY.register("oolite", () -> new OoliteBlock());
	public static final RegistryObject<Block> PHOSPHORITE = REGISTRY.register("phosphorite", () -> new PhosphoriteBlock());
	public static final RegistryObject<Block> SANDSTONE = REGISTRY.register("sandstone", () -> new SandstoneBlock());
	public static final RegistryObject<Block> SHALE = REGISTRY.register("shale", () -> new ShaleBlock());
	public static final RegistryObject<Block> SILTSTONE = REGISTRY.register("siltstone", () -> new SiltstoneBlock());
	public static final RegistryObject<Block> SYLVINITE = REGISTRY.register("sylvinite", () -> new SylviniteBlock());
	public static final RegistryObject<Block> TILLITE = REGISTRY.register("tillite", () -> new TilliteBlock());
	public static final RegistryObject<Block> TRAVERTINE = REGISTRY.register("travertine", () -> new TravertineBlock());
	public static final RegistryObject<Block> TUFA = REGISTRY.register("tufa", () -> new TufaBlock());
	public static final RegistryObject<Block> TURBIDITE = REGISTRY.register("turbidite", () -> new TurbiditeBlock());
	public static final RegistryObject<Block> WACKESTONE = REGISTRY.register("wackestone", () -> new WackestoneBlock());
	public static final RegistryObject<Block> ANTHRACITE = REGISTRY.register("anthracite", () -> new AnthraciteBlock());
	public static final RegistryObject<Block> AMPHIBOLITE = REGISTRY.register("amphibolite", () -> new AmphiboliteBlock());
	public static final RegistryObject<Block> BLUESCHIST = REGISTRY.register("blueschist", () -> new BlueschistBlock());
	public static final RegistryObject<Block> CATACLASITE = REGISTRY.register("cataclasite", () -> new CataclasiteBlock());
	public static final RegistryObject<Block> ECLOGITE = REGISTRY.register("eclogite", () -> new EclogiteBlock());
	public static final RegistryObject<Block> GNEISS = REGISTRY.register("gneiss", () -> new GneissBlock());
	public static final RegistryObject<Block> GRANULITE = REGISTRY.register("granulite", () -> new GranuliteBlock());
	public static final RegistryObject<Block> GREENSCHIST = REGISTRY.register("greenschist", () -> new GreenschistBlock());
	public static final RegistryObject<Block> HORNFELS = REGISTRY.register("hornfels", () -> new HornfelsBlock());
	public static final RegistryObject<Block> CALCFLINTA = REGISTRY.register("calcflinta", () -> new CalcflintaBlock());
	public static final RegistryObject<Block> LITCHFIELDITE = REGISTRY.register("litchfieldite", () -> new LitchfielditeBlock());
	public static final RegistryObject<Block> MARBLE = REGISTRY.register("marble", () -> new MarbleBlock());
	public static final RegistryObject<Block> MIGMATITE = REGISTRY.register("migmatite", () -> new MigmatiteBlock());
	public static final RegistryObject<Block> MYLONITE = REGISTRY.register("mylonite", () -> new MyloniteBlock());
	public static final RegistryObject<Block> METAPELITE = REGISTRY.register("metapelite", () -> new MetapeliteBlock());
	public static final RegistryObject<Block> METAPSAMMITE = REGISTRY.register("metapsammite", () -> new MetapsammiteBlock());
	public static final RegistryObject<Block> PHYLLITE = REGISTRY.register("phyllite", () -> new PhylliteBlock());
	public static final RegistryObject<Block> PSEUDOTACHYLITE = REGISTRY.register("pseudotachylite", () -> new PseudotachyliteBlock());
	public static final RegistryObject<Block> QUARTZITE = REGISTRY.register("quartzite", () -> new QuartziteBlock());
	public static final RegistryObject<Block> SCHIST = REGISTRY.register("schist", () -> new SchistBlock());
	public static final RegistryObject<Block> SERPENTINITE = REGISTRY.register("serpentinite", () -> new SerpentiniteBlock());
	public static final RegistryObject<Block> SKARN = REGISTRY.register("skarn", () -> new SkarnBlock());
	public static final RegistryObject<Block> SLATE = REGISTRY.register("slate", () -> new SlateBlock());
	public static final RegistryObject<Block> SUEVITE = REGISTRY.register("suevite", () -> new SueviteBlock());
	public static final RegistryObject<Block> SOAPSTONE = REGISTRY.register("soapstone", () -> new SoapstoneBlock());
	public static final RegistryObject<Block> TECTONITE = REGISTRY.register("tectonite", () -> new TectoniteBlock());
	public static final RegistryObject<Block> WHITESCHIST = REGISTRY.register("whiteschist", () -> new WhiteschistBlock());
	public static final RegistryObject<Block> ADAMELLITE = REGISTRY.register("adamellite", () -> new AdamelliteBlock());
	public static final RegistryObject<Block> APPINITE = REGISTRY.register("appinite", () -> new AppiniteBlock());
	public static final RegistryObject<Block> APHANITE = REGISTRY.register("aphanite", () -> new AphaniteBlock());
	public static final RegistryObject<Block> BOROLANITE = REGISTRY.register("borolanite", () -> new BorolaniteBlock());
	public static final RegistryObject<Block> EPIDOSITE = REGISTRY.register("epidosite", () -> new EpidositeBlock());
	public static final RegistryObject<Block> FELSITE = REGISTRY.register("felsite", () -> new FelsiteBlock());
	public static final RegistryObject<Block> GANISTER = REGISTRY.register("ganister", () -> new GanisterBlock());
	public static final RegistryObject<Block> GOSSAN = REGISTRY.register("gossan", () -> new GossanBlock());
	public static final RegistryObject<Block> JADEITITE = REGISTRY.register("jadeitite", () -> new JadeititeBlock());
	public static final RegistryObject<Block> JASPEROID = REGISTRY.register("jasperoid", () -> new JasperoidBlock());
	public static final RegistryObject<Block> KENYTE = REGISTRY.register("kenyte", () -> new KenyteBlock());
	public static final RegistryObject<Block> LARVIKITE = REGISTRY.register("larvikite", () -> new LarvikiteBlock());
	public static final RegistryObject<Block> LLANITE = REGISTRY.register("llanite", () -> new LlaniteBlock());
	public static final RegistryObject<Block> LUXULLIANITE = REGISTRY.register("luxullianite", () -> new LuxullianiteBlock());
	public static final RegistryObject<Block> MANGERITE = REGISTRY.register("mangerite", () -> new MangeriteBlock());
	public static final RegistryObject<Block> NOVACULITE = REGISTRY.register("novaculite", () -> new NovaculiteBlock());
	public static final RegistryObject<Block> PIETERSITE = REGISTRY.register("pietersite", () -> new PietersiteBlock());
	public static final RegistryObject<Block> PYROLITE = REGISTRY.register("pyrolite", () -> new PyroliteBlock());
	public static final RegistryObject<Block> RODINGITE = REGISTRY.register("rodingite", () -> new RodingiteBlock());
	public static final RegistryObject<Block> TACONITE = REGISTRY.register("taconite", () -> new TaconiteBlock());
	public static final RegistryObject<Block> TACHYLITE = REGISTRY.register("tachylite", () -> new TachyliteBlock());
	public static final RegistryObject<Block> TESCHENITE = REGISTRY.register("teschenite", () -> new TescheniteBlock());
	public static final RegistryObject<Block> THERALITE = REGISTRY.register("theralite", () -> new TheraliteBlock());
	public static final RegistryObject<Block> UNAKITE = REGISTRY.register("unakite", () -> new UnakiteBlock());
	public static final RegistryObject<Block> VARIOLITE = REGISTRY.register("variolite", () -> new VarioliteBlock());
	public static final RegistryObject<Block> WAD = REGISTRY.register("wad", () -> new WadBlock());
	public static final RegistryObject<Block> FLUVISOLS = REGISTRY.register("fluvisols", () -> new FluvisolsBlock());
	public static final RegistryObject<Block> RENDZINAS = REGISTRY.register("rendzinas", () -> new RendzinasBlock());
	public static final RegistryObject<Block> DURISOLS = REGISTRY.register("durisols", () -> new DurisolsBlock());
	public static final RegistryObject<Block> ARENOSOLS = REGISTRY.register("arenosols", () -> new ArenosolsBlock());
	public static final RegistryObject<Block> PELISOLS = REGISTRY.register("pelisols", () -> new PelisolsBlock());
	public static final RegistryObject<Block> STAGNOSOLS = REGISTRY.register("stagnosols", () -> new StagnosolsBlock());
	public static final RegistryObject<Block> CRYOSOLS = REGISTRY.register("cryosols", () -> new CryosolsBlock());
	public static final RegistryObject<Block> HISTOSOLS = REGISTRY.register("histosols", () -> new HistosolsBlock());
	public static final RegistryObject<Block> LIXISOLS = REGISTRY.register("lixisols", () -> new LixisolsBlock());
	public static final RegistryObject<Block> ALBELUVISOLS = REGISTRY.register("albeluvisols", () -> new AlbeluvisolsBlock());
}
