
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.zachsedit.lifealikes.init;

import org.lwjgl.openal.AL;

import org.checkerframework.checker.units.qual.K;
import org.checkerframework.checker.units.qual.C;

import org.apache.http.cookie.SM;

import net.zachsedit.lifealikes.item.ZunyiteItem;
import net.zachsedit.lifealikes.item.ZrItem;
import net.zachsedit.lifealikes.item.ZoisiteItem;
import net.zachsedit.lifealikes.item.ZnItem;
import net.zachsedit.lifealikes.item.ZirconiaItem;
import net.zachsedit.lifealikes.item.ZirconItem;
import net.zachsedit.lifealikes.item.ZektzeriteItem;
import net.zachsedit.lifealikes.item.YbItem;
import net.zachsedit.lifealikes.item.YItem;
import net.zachsedit.lifealikes.item.YAGItem;
import net.zachsedit.lifealikes.item.XonotliteItem;
import net.zachsedit.lifealikes.item.XeItem;
import net.zachsedit.lifealikes.item.WillemiteItem;
import net.zachsedit.lifealikes.item.WItem;
import net.zachsedit.lifealikes.item.VlasoviteItem;
import net.zachsedit.lifealikes.item.VivianiteItem;
import net.zachsedit.lifealikes.item.VesuvianiteItem;
import net.zachsedit.lifealikes.item.VItem;
import net.zachsedit.lifealikes.item.UvaroviteItem;
import net.zachsedit.lifealikes.item.UItem;
import net.zachsedit.lifealikes.item.TurquoiseItem;
import net.zachsedit.lifealikes.item.TurmalineItem;
import net.zachsedit.lifealikes.item.TugtupiteItem;
import net.zachsedit.lifealikes.item.TsItem;
import net.zachsedit.lifealikes.item.TremoliteItem;
import net.zachsedit.lifealikes.item.TopazItem;
import net.zachsedit.lifealikes.item.TmItem;
import net.zachsedit.lifealikes.item.TlItem;
import net.zachsedit.lifealikes.item.TinzeniteItem;
import net.zachsedit.lifealikes.item.TiItem;
import net.zachsedit.lifealikes.item.ThorianiteItem;
import net.zachsedit.lifealikes.item.ThItem;
import net.zachsedit.lifealikes.item.TephroiteItem;
import net.zachsedit.lifealikes.item.TeItem;
import net.zachsedit.lifealikes.item.TcItem;
import net.zachsedit.lifealikes.item.TbItem;
import net.zachsedit.lifealikes.item.TanzaniteItem;
import net.zachsedit.lifealikes.item.TantaliteItem;
import net.zachsedit.lifealikes.item.TalcItem;
import net.zachsedit.lifealikes.item.TaafeiteItem;
import net.zachsedit.lifealikes.item.TaItem;
import net.zachsedit.lifealikes.item.SulphurItem;
import net.zachsedit.lifealikes.item.SugiliteItem;
import net.zachsedit.lifealikes.item.StibiotantaliteItem;
import net.zachsedit.lifealikes.item.StauroliteItem;
import net.zachsedit.lifealikes.item.SrItem;
import net.zachsedit.lifealikes.item.SpodumeneItem;
import net.zachsedit.lifealikes.item.SpinelItem;
import net.zachsedit.lifealikes.item.SpessartineItem;
import net.zachsedit.lifealikes.item.SogdianiteItem;
import net.zachsedit.lifealikes.item.SodaliteItem;
import net.zachsedit.lifealikes.item.SnItem;
import net.zachsedit.lifealikes.item.SmaragditeItem;
import net.zachsedit.lifealikes.item.SmItem;
import net.zachsedit.lifealikes.item.SinhaliteItem;
import net.zachsedit.lifealikes.item.SimpsoniteItem;
import net.zachsedit.lifealikes.item.SillimaniteItem;
import net.zachsedit.lifealikes.item.SiItem;
import net.zachsedit.lifealikes.item.SgItem;
import net.zachsedit.lifealikes.item.SerendibiteItem;
import net.zachsedit.lifealikes.item.SekaninaiteItem;
import net.zachsedit.lifealikes.item.SeItem;
import net.zachsedit.lifealikes.item.ScorzaliteItem;
import net.zachsedit.lifealikes.item.SchorlomiteItem;
import net.zachsedit.lifealikes.item.ScapoliteItem;
import net.zachsedit.lifealikes.item.ScItem;
import net.zachsedit.lifealikes.item.SbItem;
import net.zachsedit.lifealikes.item.SarcoliteItem;
import net.zachsedit.lifealikes.item.SapphirineItem;
import net.zachsedit.lifealikes.item.SapphireItem;
import net.zachsedit.lifealikes.item.SanidineItem;
import net.zachsedit.lifealikes.item.SamarskiteItem;
import net.zachsedit.lifealikes.item.SItem;
import net.zachsedit.lifealikes.item.RutileItem;
import net.zachsedit.lifealikes.item.RubyItem;
import net.zachsedit.lifealikes.item.RuItem;
import net.zachsedit.lifealikes.item.RnItem;
import net.zachsedit.lifealikes.item.RichteriteItem;
import net.zachsedit.lifealikes.item.RhodocniteItem;
import net.zachsedit.lifealikes.item.RhodiziteItem;
import net.zachsedit.lifealikes.item.RhItem;
import net.zachsedit.lifealikes.item.RgItem;
import net.zachsedit.lifealikes.item.RfItem;
import net.zachsedit.lifealikes.item.RealgarItem;
import net.zachsedit.lifealikes.item.ReItem;
import net.zachsedit.lifealikes.item.RbItem;
import net.zachsedit.lifealikes.item.RaItem;
import net.zachsedit.lifealikes.item.PyroxmangiteItem;
import net.zachsedit.lifealikes.item.PyrophylliteItem;
import net.zachsedit.lifealikes.item.PyropeItem;
import net.zachsedit.lifealikes.item.PyrolusiteItem;
import net.zachsedit.lifealikes.item.PyriteItem;
import net.zachsedit.lifealikes.item.PumpellyiteItem;
import net.zachsedit.lifealikes.item.PuItem;
import net.zachsedit.lifealikes.item.PtItem;
import net.zachsedit.lifealikes.item.PrehniteItem;
import net.zachsedit.lifealikes.item.PrItem;
import net.zachsedit.lifealikes.item.PovondraiteItem;
import net.zachsedit.lifealikes.item.PolluciteItem;
import net.zachsedit.lifealikes.item.PoItem;
import net.zachsedit.lifealikes.item.PmItem;
import net.zachsedit.lifealikes.item.PhenakiteItem;
import net.zachsedit.lifealikes.item.PetaliteItem;
import net.zachsedit.lifealikes.item.PeridotItem;
import net.zachsedit.lifealikes.item.PericlaseItem;
import net.zachsedit.lifealikes.item.PdItem;
import net.zachsedit.lifealikes.item.PbItem;
import net.zachsedit.lifealikes.item.PargasiteItem;
import net.zachsedit.lifealikes.item.PalygorskiteItem;
import net.zachsedit.lifealikes.item.PainiteItem;
import net.zachsedit.lifealikes.item.PaItem;
import net.zachsedit.lifealikes.item.PItem;
import net.zachsedit.lifealikes.item.OsItem;
import net.zachsedit.lifealikes.item.OpalItem;
import net.zachsedit.lifealikes.item.OligoclaseItem;
import net.zachsedit.lifealikes.item.OgItem;
import net.zachsedit.lifealikes.item.OItem;
import net.zachsedit.lifealikes.item.NpItem;
import net.zachsedit.lifealikes.item.NorbergiteItem;
import net.zachsedit.lifealikes.item.NoItem;
import net.zachsedit.lifealikes.item.NiItem;
import net.zachsedit.lifealikes.item.NhItem;
import net.zachsedit.lifealikes.item.NeptuniteItem;
import net.zachsedit.lifealikes.item.NephriteItem;
import net.zachsedit.lifealikes.item.NephelineItem;
import net.zachsedit.lifealikes.item.NeItem;
import net.zachsedit.lifealikes.item.NdItem;
import net.zachsedit.lifealikes.item.NbItem;
import net.zachsedit.lifealikes.item.NatromontebrasiteItem;
import net.zachsedit.lifealikes.item.NambuliteItem;
import net.zachsedit.lifealikes.item.NaItem;
import net.zachsedit.lifealikes.item.NItem;
import net.zachsedit.lifealikes.item.MtItem;
import net.zachsedit.lifealikes.item.MontebrasiteItem;
import net.zachsedit.lifealikes.item.MoldaviteItem;
import net.zachsedit.lifealikes.item.MoItem;
import net.zachsedit.lifealikes.item.MnItem;
import net.zachsedit.lifealikes.item.MilariteItem;
import net.zachsedit.lifealikes.item.MicroclineItem;
import net.zachsedit.lifealikes.item.MgItem;
import net.zachsedit.lifealikes.item.MeloniteItem;
import net.zachsedit.lifealikes.item.MeioniteItem;
import net.zachsedit.lifealikes.item.MdItem;
import net.zachsedit.lifealikes.item.McItem;
import net.zachsedit.lifealikes.item.MarialiteItem;
import net.zachsedit.lifealikes.item.MarcasiteItem;
import net.zachsedit.lifealikes.item.ManganotantaliteItem;
import net.zachsedit.lifealikes.item.MagnetiteItem;
import net.zachsedit.lifealikes.item.MagnesiochromiteItem;
import net.zachsedit.lifealikes.item.LvItem;
import net.zachsedit.lifealikes.item.LuItem;
import net.zachsedit.lifealikes.item.LrItem;
import net.zachsedit.lifealikes.item.LinobateItem;
import net.zachsedit.lifealikes.item.LiItem;
import net.zachsedit.lifealikes.item.LeuciteItem;
import net.zachsedit.lifealikes.item.LazuliteItem;
import net.zachsedit.lifealikes.item.LawsoniteItem;
import net.zachsedit.lifealikes.item.LabradoriteItem;
import net.zachsedit.lifealikes.item.LaItem;
import net.zachsedit.lifealikes.item.KunziteItem;
import net.zachsedit.lifealikes.item.KrItem;
import net.zachsedit.lifealikes.item.KornerupineItem;
import net.zachsedit.lifealikes.item.KItem;
import net.zachsedit.lifealikes.item.JeremejeviteItem;
import net.zachsedit.lifealikes.item.JasperItem;
import net.zachsedit.lifealikes.item.JadeiteItem;
import net.zachsedit.lifealikes.item.IrItem;
import net.zachsedit.lifealikes.item.InItem;
import net.zachsedit.lifealikes.item.IlmeniteItem;
import net.zachsedit.lifealikes.item.IItem;
import net.zachsedit.lifealikes.item.HyperstheneTESTItem;
import net.zachsedit.lifealikes.item.HyalophaneItem;
import net.zachsedit.lifealikes.item.HurlbutiteItem;
import net.zachsedit.lifealikes.item.HumiteItem;
import net.zachsedit.lifealikes.item.HsItem;
import net.zachsedit.lifealikes.item.HornblendeItem;
import net.zachsedit.lifealikes.item.HoltiteItem;
import net.zachsedit.lifealikes.item.HoItem;
import net.zachsedit.lifealikes.item.HiddeniteItem;
import net.zachsedit.lifealikes.item.HgItem;
import net.zachsedit.lifealikes.item.HfItem;
import net.zachsedit.lifealikes.item.HematiteItem;
import net.zachsedit.lifealikes.item.HelviteItem;
import net.zachsedit.lifealikes.item.HedenbergiteItem;
import net.zachsedit.lifealikes.item.HeItem;
import net.zachsedit.lifealikes.item.HancockiteItem;
import net.zachsedit.lifealikes.item.HambergiteItem;
import net.zachsedit.lifealikes.item.HItem;
import net.zachsedit.lifealikes.item.GrossularItem;
import net.zachsedit.lifealikes.item.GrandidieriteItem;
import net.zachsedit.lifealikes.item.GoethiteItem;
import net.zachsedit.lifealikes.item.GeItem;
import net.zachsedit.lifealikes.item.GdItem;
import net.zachsedit.lifealikes.item.GarnetItem;
import net.zachsedit.lifealikes.item.GalaxiteItem;
import net.zachsedit.lifealikes.item.GahniteItem;
import net.zachsedit.lifealikes.item.GadoliniteItem;
import net.zachsedit.lifealikes.item.GaItem;
import net.zachsedit.lifealikes.item.GGGItem;
import net.zachsedit.lifealikes.item.FrItem;
import net.zachsedit.lifealikes.item.ForsteriteItem;
import net.zachsedit.lifealikes.item.FmItem;
import net.zachsedit.lifealikes.item.FlItem;
import net.zachsedit.lifealikes.item.FerrosiliteItem;
import net.zachsedit.lifealikes.item.FergusoniteItem;
import net.zachsedit.lifealikes.item.FeItem;
import net.zachsedit.lifealikes.item.FabuliteItem;
import net.zachsedit.lifealikes.item.FItem;
import net.zachsedit.lifealikes.item.EuxeniteItem;
import net.zachsedit.lifealikes.item.EudialyteItem;
import net.zachsedit.lifealikes.item.EuclaseItem;
import net.zachsedit.lifealikes.item.EuItem;
import net.zachsedit.lifealikes.item.EsItem;
import net.zachsedit.lifealikes.item.ErItem;
import net.zachsedit.lifealikes.item.EpidoteItem;
import net.zachsedit.lifealikes.item.EnstatiteItem;
import net.zachsedit.lifealikes.item.DyItem;
import net.zachsedit.lifealikes.item.DurangiteItem;
import net.zachsedit.lifealikes.item.DumortieriteItem;
import net.zachsedit.lifealikes.item.DsItem;
import net.zachsedit.lifealikes.item.DiopsideItem;
import net.zachsedit.lifealikes.item.DiasporeItem;
import net.zachsedit.lifealikes.item.DbItem;
import net.zachsedit.lifealikes.item.DaviditeItem;
import net.zachsedit.lifealikes.item.DatoliteItem;
import net.zachsedit.lifealikes.item.DanburiteItem;
import net.zachsedit.lifealikes.item.CuItem;
import net.zachsedit.lifealikes.item.CsItem;
import net.zachsedit.lifealikes.item.CrItem;
import net.zachsedit.lifealikes.item.CovelliteItem;
import net.zachsedit.lifealikes.item.CordieriteItem;
import net.zachsedit.lifealikes.item.CobaltiteItem;
import net.zachsedit.lifealikes.item.CoItem;
import net.zachsedit.lifealikes.item.CnItem;
import net.zachsedit.lifealikes.item.CmItem;
import net.zachsedit.lifealikes.item.ClinozoisiteItem;
import net.zachsedit.lifealikes.item.ClinohumiteItem;
import net.zachsedit.lifealikes.item.ClinoenstatiteItem;
import net.zachsedit.lifealikes.item.ClItem;
import net.zachsedit.lifealikes.item.CitrineItem;
import net.zachsedit.lifealikes.item.ChrysopraseItem;
import net.zachsedit.lifealikes.item.ChrysoberyllItem;
import net.zachsedit.lifealikes.item.ChromiteItem;
import net.zachsedit.lifealikes.item.ChromdraviteItem;
import net.zachsedit.lifealikes.item.ChondroiteItem;
import net.zachsedit.lifealikes.item.ChambersiteItem;
import net.zachsedit.lifealikes.item.ChalcedonyItem;
import net.zachsedit.lifealikes.item.CfItem;
import net.zachsedit.lifealikes.item.CeItem;
import net.zachsedit.lifealikes.item.CdItem;
import net.zachsedit.lifealikes.item.CatapleiiteItem;
import net.zachsedit.lifealikes.item.CassiteriteItem;
import net.zachsedit.lifealikes.item.CancriniteItem;
import net.zachsedit.lifealikes.item.CanasiteItem;
import net.zachsedit.lifealikes.item.CaItem;
import net.zachsedit.lifealikes.item.CItem;
import net.zachsedit.lifealikes.item.BytowniteItem;
import net.zachsedit.lifealikes.item.BustamiteItem;
import net.zachsedit.lifealikes.item.BrookiteItem;
import net.zachsedit.lifealikes.item.BronziteItem;
import net.zachsedit.lifealikes.item.BreithauptiteItem;
import net.zachsedit.lifealikes.item.BrazilianiteItem;
import net.zachsedit.lifealikes.item.BrItem;
import net.zachsedit.lifealikes.item.BoraciteItem;
import net.zachsedit.lifealikes.item.BixbyiteItem;
import net.zachsedit.lifealikes.item.BiItem;
import net.zachsedit.lifealikes.item.BhItem;
import net.zachsedit.lifealikes.item.BerylloniteItem;
import net.zachsedit.lifealikes.item.BenitoiteItem;
import net.zachsedit.lifealikes.item.BeItem;
import net.zachsedit.lifealikes.item.BaItem;
import net.zachsedit.lifealikes.item.BItem;
import net.zachsedit.lifealikes.item.AxiniteItem;
import net.zachsedit.lifealikes.item.AventurineItem;
import net.zachsedit.lifealikes.item.AuItem;
import net.zachsedit.lifealikes.item.AtItem;
import net.zachsedit.lifealikes.item.AsItem;
import net.zachsedit.lifealikes.item.ArItem;
import net.zachsedit.lifealikes.item.AnorthoclaseItem;
import net.zachsedit.lifealikes.item.AndesineItem;
import net.zachsedit.lifealikes.item.AndalusiteItem;
import net.zachsedit.lifealikes.item.AnataseItem;
import net.zachsedit.lifealikes.item.AnalcimeItem;
import net.zachsedit.lifealikes.item.AmethystItem;
import net.zachsedit.lifealikes.item.AmblygoniteItem;
import net.zachsedit.lifealikes.item.AmazoniteItem;
import net.zachsedit.lifealikes.item.AmItem;
import net.zachsedit.lifealikes.item.AlmandineItem;
import net.zachsedit.lifealikes.item.AllaniteItem;
import net.zachsedit.lifealikes.item.AlexandriteItem;
import net.zachsedit.lifealikes.item.AlItem;
import net.zachsedit.lifealikes.item.AgItem;
import net.zachsedit.lifealikes.item.AeschyniteItem;
import net.zachsedit.lifealikes.item.AegirineItem;
import net.zachsedit.lifealikes.item.ActinoliteItem;
import net.zachsedit.lifealikes.item.AcItem;
import net.zachsedit.lifealikes.LifealikesMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

public class LifealikesModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, LifealikesMod.MODID);
	public static final RegistryObject<Item> HE = REGISTRY.register("he", () -> new HeItem());
	public static final RegistryObject<Item> ILMENITE = REGISTRY.register("ilmenite", () -> new IlmeniteItem());
	public static final RegistryObject<Item> RUBY = REGISTRY.register("ruby", () -> new RubyItem());
	public static final RegistryObject<Item> SAPPHIRE = REGISTRY.register("sapphire", () -> new SapphireItem());
	public static final RegistryObject<Item> LAZULITE = REGISTRY.register("lazulite", () -> new LazuliteItem());
	public static final RegistryObject<Item> ALEXANDRITE = REGISTRY.register("alexandrite", () -> new AlexandriteItem());
	public static final RegistryObject<Item> NEPHELINE = REGISTRY.register("nepheline", () -> new NephelineItem());
	public static final RegistryObject<Item> CHRYSOBERYLL = REGISTRY.register("chrysoberyll", () -> new ChrysoberyllItem());
	public static final RegistryObject<Item> NEPTUNITE = REGISTRY.register("neptunite", () -> new NeptuniteItem());
	public static final RegistryObject<Item> HOLTITE = REGISTRY.register("holtite", () -> new HoltiteItem());
	public static final RegistryObject<Item> PARGASITE = REGISTRY.register("pargasite", () -> new PargasiteItem());
	public static final RegistryObject<Item> YAG = REGISTRY.register("yag", () -> new YAGItem());
	public static final RegistryObject<Item> RICHTERITE = REGISTRY.register("richterite", () -> new RichteriteItem());
	public static final RegistryObject<Item> ZIRCONIA = REGISTRY.register("zirconia", () -> new ZirconiaItem());
	public static final RegistryObject<Item> SAMARSKITE = REGISTRY.register("samarskite", () -> new SamarskiteItem());
	public static final RegistryObject<Item> RHODIZITE = REGISTRY.register("rhodizite", () -> new RhodiziteItem());
	public static final RegistryObject<Item> STIBIOTANTALITE = REGISTRY.register("stibiotantalite", () -> new StibiotantaliteItem());
	public static final RegistryObject<Item> TAAFEITE = REGISTRY.register("taafeite", () -> new TaafeiteItem());
	public static final RegistryObject<Item> TREMOLITE = REGISTRY.register("tremolite", () -> new TremoliteItem());
	public static final RegistryObject<Item> SPINEL = REGISTRY.register("spinel", () -> new SpinelItem());
	public static final RegistryObject<Item> TURQUOISE = REGISTRY.register("turquoise", () -> new TurquoiseItem());
	public static final RegistryObject<Item> TOPAZ = REGISTRY.register("topaz", () -> new TopazItem());
	public static final RegistryObject<Item> ANALCIME = REGISTRY.register("analcime", () -> new AnalcimeItem());
	public static final RegistryObject<Item> DATOLITE = REGISTRY.register("datolite", () -> new DatoliteItem());
	public static final RegistryObject<Item> DURANGITE = REGISTRY.register("durangite", () -> new DurangiteItem());
	public static final RegistryObject<Item> EUDIALYTE = REGISTRY.register("eudialyte", () -> new EudialyteItem());
	public static final RegistryObject<Item> GAHNITE = REGISTRY.register("gahnite", () -> new GahniteItem());
	public static final RegistryObject<Item> GOETHITE = REGISTRY.register("goethite", () -> new GoethiteItem());
	public static final RegistryObject<Item> GALAXITE = REGISTRY.register("galaxite", () -> new GalaxiteItem());
	public static final RegistryObject<Item> PAINITE = REGISTRY.register("painite", () -> new PainiteItem());
	public static final RegistryObject<Item> PHENAKITE = REGISTRY.register("phenakite", () -> new PhenakiteItem());
	public static final RegistryObject<Item> ANDALUSITE = REGISTRY.register("andalusite", () -> new AndalusiteItem());
	public static final RegistryObject<Item> EUCLASE = REGISTRY.register("euclase", () -> new EuclaseItem());
	public static final RegistryObject<Item> HAMBERGITE = REGISTRY.register("hambergite", () -> new HambergiteItem());
	public static final RegistryObject<Item> SAPPHIRINE = REGISTRY.register("sapphirine", () -> new SapphirineItem());
	public static final RegistryObject<Item> DUMORTIERITE = REGISTRY.register("dumortierite", () -> new DumortieriteItem());
	public static final RegistryObject<Item> ALMANDINE = REGISTRY.register("almandine", () -> new AlmandineItem());
	public static final RegistryObject<Item> BORACITE = REGISTRY.register("boracite", () -> new BoraciteItem());
	public static final RegistryObject<Item> CORDIERITE = REGISTRY.register("cordierite", () -> new CordieriteItem());
	public static final RegistryObject<Item> DANBURITE = REGISTRY.register("danburite", () -> new DanburiteItem());
	public static final RegistryObject<Item> GRANDIDIERITE = REGISTRY.register("grandidierite", () -> new GrandidieriteItem());
	public static final RegistryObject<Item> PYROPE = REGISTRY.register("pyrope", () -> new PyropeItem());
	public static final RegistryObject<Item> SCHORLOMITE = REGISTRY.register("schorlomite", () -> new SchorlomiteItem());
	public static final RegistryObject<Item> SEKANINAITE = REGISTRY.register("sekaninaite", () -> new SekaninaiteItem());
	public static final RegistryObject<Item> SIMPSONITE = REGISTRY.register("simpsonite", () -> new SimpsoniteItem());
	public static final RegistryObject<Item> SPESSARTINE = REGISTRY.register("spessartine", () -> new SpessartineItem());
	public static final RegistryObject<Item> STAUROLITE = REGISTRY.register("staurolite", () -> new StauroliteItem());
	public static final RegistryObject<Item> TURMALINE = REGISTRY.register("turmaline", () -> new TurmalineItem());
	public static final RegistryObject<Item> UVAROVITE = REGISTRY.register("uvarovite", () -> new UvaroviteItem());
	public static final RegistryObject<Item> AMETHYST = REGISTRY.register("amethyst", () -> new AmethystItem());
	public static final RegistryObject<Item> AVENTURINE = REGISTRY.register("aventurine", () -> new AventurineItem());
	public static final RegistryObject<Item> CHAMBERSITE = REGISTRY.register("chambersite", () -> new ChambersiteItem());
	public static final RegistryObject<Item> CHROMDRAVITE = REGISTRY.register("chromdravite", () -> new ChromdraviteItem());
	public static final RegistryObject<Item> CITRINE = REGISTRY.register("citrine", () -> new CitrineItem());
	public static final RegistryObject<Item> FORSTERITE = REGISTRY.register("forsterite", () -> new ForsteriteItem());
	public static final RegistryObject<Item> POVONDRAITE = REGISTRY.register("povondraite", () -> new PovondraiteItem());
	public static final RegistryObject<Item> ZUNYITE = REGISTRY.register("zunyite", () -> new ZunyiteItem());
	public static final RegistryObject<Item> GARNET = REGISTRY.register("garnet", () -> new GarnetItem());
	public static final RegistryObject<Item> JEREMEJEVITE = REGISTRY.register("jeremejevite", () -> new JeremejeviteItem());
	public static final RegistryObject<Item> SILLIMANITE = REGISTRY.register("sillimanite", () -> new SillimaniteItem());
	public static final RegistryObject<Item> ZIRCON = REGISTRY.register("zircon", () -> new ZirconItem());
	public static final RegistryObject<Item> AXINITE = REGISTRY.register("axinite", () -> new AxiniteItem());
	public static final RegistryObject<Item> CHALCEDONY = REGISTRY.register("chalcedony", () -> new ChalcedonyItem());
	public static final RegistryObject<Item> CHRYSOPRASE = REGISTRY.register("chrysoprase", () -> new ChrysopraseItem());
	public static final RegistryObject<Item> DIASPORE = REGISTRY.register("diaspore", () -> new DiasporeItem());
	public static final RegistryObject<Item> GADOLINITE = REGISTRY.register("gadolinite", () -> new GadoliniteItem());
	public static final RegistryObject<Item> GROSSULAR = REGISTRY.register("grossular", () -> new GrossularItem());
	public static final RegistryObject<Item> HIDDENITE = REGISTRY.register("hiddenite", () -> new HiddeniteItem());
	public static final RegistryObject<Item> JADEITE = REGISTRY.register("jadeite", () -> new JadeiteItem());
	public static final RegistryObject<Item> JASPER = REGISTRY.register("jasper", () -> new JasperItem());
	public static final RegistryObject<Item> KORNERUPINE = REGISTRY.register("kornerupine", () -> new KornerupineItem());
	public static final RegistryObject<Item> KUNZITE = REGISTRY.register("kunzite", () -> new KunziteItem());
	public static final RegistryObject<Item> PERIDOT = REGISTRY.register("peridot", () -> new PeridotItem());
	public static final RegistryObject<Item> POLLUCITE = REGISTRY.register("pollucite", () -> new PolluciteItem());
	public static final RegistryObject<Item> SERENDIBITE = REGISTRY.register("serendibite", () -> new SerendibiteItem());
	public static final RegistryObject<Item> SINHALITE = REGISTRY.register("sinhalite", () -> new SinhaliteItem());
	public static final RegistryObject<Item> SPODUMENE = REGISTRY.register("spodumene", () -> new SpodumeneItem());
	public static final RegistryObject<Item> TANZANITE = REGISTRY.register("tanzanite", () -> new TanzaniteItem());
	public static final RegistryObject<Item> THORIANITE = REGISTRY.register("thorianite", () -> new ThorianiteItem());
	public static final RegistryObject<Item> TINZENITE = REGISTRY.register("tinzenite", () -> new TinzeniteItem());
	public static final RegistryObject<Item> GGG = REGISTRY.register("ggg", () -> new GGGItem());
	public static final RegistryObject<Item> NAMBULITE = REGISTRY.register("nambulite", () -> new NambuliteItem());
	public static final RegistryObject<Item> VESUVIANITE = REGISTRY.register("vesuvianite", () -> new VesuvianiteItem());
	public static final RegistryObject<Item> CASSITERITE = REGISTRY.register("cassiterite", () -> new CassiteriteItem());
	public static final RegistryObject<Item> CLINOZOISITE = REGISTRY.register("clinozoisite", () -> new ClinozoisiteItem());
	public static final RegistryObject<Item> EPIDOTE = REGISTRY.register("epidote", () -> new EpidoteItem());
	public static final RegistryObject<Item> HANCOCKITE = REGISTRY.register("hancockite", () -> new HancockiteItem());
	public static final RegistryObject<Item> PYROLUSITE = REGISTRY.register("pyrolusite", () -> new PyrolusiteItem());
	public static final RegistryObject<Item> SOGDIANITE = REGISTRY.register("sogdianite", () -> new SogdianiteItem());
	public static final RegistryObject<Item> AMAZONITE = REGISTRY.register("amazonite", () -> new AmazoniteItem());
	public static final RegistryObject<Item> ANDESINE = REGISTRY.register("andesine", () -> new AndesineItem());
	public static final RegistryObject<Item> ANORTHOCLASE = REGISTRY.register("anorthoclase", () -> new AnorthoclaseItem());
	public static final RegistryObject<Item> BENITOITE = REGISTRY.register("benitoite", () -> new BenitoiteItem());
	public static final RegistryObject<Item> BIXBYITE = REGISTRY.register("bixbyite", () -> new BixbyiteItem());
	public static final RegistryObject<Item> BYTOWNITE = REGISTRY.register("bytownite", () -> new BytowniteItem());
	public static final RegistryObject<Item> CHONDROITE = REGISTRY.register("chondroite", () -> new ChondroiteItem());
	public static final RegistryObject<Item> HELVITE = REGISTRY.register("helvite", () -> new HelviteItem());
	public static final RegistryObject<Item> HYALOPHANE = REGISTRY.register("hyalophane", () -> new HyalophaneItem());
	public static final RegistryObject<Item> LABRADORITE = REGISTRY.register("labradorite", () -> new LabradoriteItem());
	public static final RegistryObject<Item> MARCASITE = REGISTRY.register("marcasite", () -> new MarcasiteItem());
	public static final RegistryObject<Item> MICROCLINE = REGISTRY.register("microcline", () -> new MicroclineItem());
	public static final RegistryObject<Item> NEPHRITE = REGISTRY.register("nephrite", () -> new NephriteItem());
	public static final RegistryObject<Item> NORBERGITE = REGISTRY.register("norbergite", () -> new NorbergiteItem());
	public static final RegistryObject<Item> OLIGOCLASE = REGISTRY.register("oligoclase", () -> new OligoclaseItem());
	public static final RegistryObject<Item> PETALITE = REGISTRY.register("petalite", () -> new PetaliteItem());
	public static final RegistryObject<Item> PREHNITE = REGISTRY.register("prehnite", () -> new PrehniteItem());
	public static final RegistryObject<Item> PYRITE = REGISTRY.register("pyrite", () -> new PyriteItem());
	public static final RegistryObject<Item> RUTILE = REGISTRY.register("rutile", () -> new RutileItem());
	public static final RegistryObject<Item> SANIDINE = REGISTRY.register("sanidine", () -> new SanidineItem());
	public static final RegistryObject<Item> SMARAGDITE = REGISTRY.register("smaragdite", () -> new SmaragditeItem());
	public static final RegistryObject<Item> SUGILITE = REGISTRY.register("sugilite", () -> new SugiliteItem());
	public static final RegistryObject<Item> TANTALITE = REGISTRY.register("tantalite", () -> new TantaliteItem());
	public static final RegistryObject<Item> XONOTLITE = REGISTRY.register("xonotlite", () -> new XonotliteItem());
	public static final RegistryObject<Item> ZOISITE = REGISTRY.register("zoisite", () -> new ZoisiteItem());
	public static final RegistryObject<Item> AEGIRINE = REGISTRY.register("aegirine", () -> new AegirineItem());
	public static final RegistryObject<Item> AMBLYGONITE = REGISTRY.register("amblygonite", () -> new AmblygoniteItem());
	public static final RegistryObject<Item> CLINOHUMITE = REGISTRY.register("clinohumite", () -> new ClinohumiteItem());
	public static final RegistryObject<Item> HUMITE = REGISTRY.register("humite", () -> new HumiteItem());
	public static final RegistryObject<Item> HURLBUTITE = REGISTRY.register("hurlbutite", () -> new HurlbutiteItem());
	public static final RegistryObject<Item> LAWSONITE = REGISTRY.register("lawsonite", () -> new LawsoniteItem());
	public static final RegistryObject<Item> PUMPELLYITE = REGISTRY.register("pumpellyite", () -> new PumpellyiteItem());
	public static final RegistryObject<Item> TEPHROITE = REGISTRY.register("tephroite", () -> new TephroiteItem());
	public static final RegistryObject<Item> VLASOVITE = REGISTRY.register("vlasovite", () -> new VlasoviteItem());
	public static final RegistryObject<Item> ZEKTZERITE = REGISTRY.register("zektzerite", () -> new ZektzeriteItem());
	public static final RegistryObject<Item> HEMATITE = REGISTRY.register("hematite", () -> new HematiteItem());
	public static final RegistryObject<Item> HEDENBERGITE = REGISTRY.register("hedenbergite", () -> new HedenbergiteItem());
	public static final RegistryObject<Item> MAGNETITE = REGISTRY.register("magnetite", () -> new MagnetiteItem());
	public static final RegistryObject<Item> MANGANOTANTALITE = REGISTRY.register("manganotantalite", () -> new ManganotantaliteItem());
	public static final RegistryObject<Item> OPAL = REGISTRY.register("opal", () -> new OpalItem());
	public static final RegistryObject<Item> RHODOCNITE = REGISTRY.register("rhodocnite", () -> new RhodocniteItem());
	public static final RegistryObject<Item> ACTINOLITE = REGISTRY.register("actinolite", () -> new ActinoliteItem());
	public static final RegistryObject<Item> ALLANITE = REGISTRY.register("allanite", () -> new AllaniteItem());
	public static final RegistryObject<Item> ANATASE = REGISTRY.register("anatase", () -> new AnataseItem());
	public static final RegistryObject<Item> BERYLLONITE = REGISTRY.register("beryllonite", () -> new BerylloniteItem());
	public static final RegistryObject<Item> BROOKITE = REGISTRY.register("brookite", () -> new BrookiteItem());
	public static final RegistryObject<Item> BUSTAMITE = REGISTRY.register("bustamite", () -> new BustamiteItem());
	public static final RegistryObject<Item> CANASITE = REGISTRY.register("canasite", () -> new CanasiteItem());
	public static final RegistryObject<Item> COBALTITE = REGISTRY.register("cobaltite", () -> new CobaltiteItem());
	public static final RegistryObject<Item> EUXENITE = REGISTRY.register("euxenite", () -> new EuxeniteItem());
	public static final RegistryObject<Item> FABULITE = REGISTRY.register("fabulite", () -> new FabuliteItem());
	public static final RegistryObject<Item> FERGUSONITE = REGISTRY.register("fergusonite", () -> new FergusoniteItem());
	public static final RegistryObject<Item> LEUCITE = REGISTRY.register("leucite", () -> new LeuciteItem());
	public static final RegistryObject<Item> MARIALITE = REGISTRY.register("marialite", () -> new MarialiteItem());
	public static final RegistryObject<Item> MEIONITE = REGISTRY.register("meionite", () -> new MeioniteItem());
	public static final RegistryObject<Item> MILARITE = REGISTRY.register("milarite", () -> new MilariteItem());
	public static final RegistryObject<Item> MONTEBRASITE = REGISTRY.register("montebrasite", () -> new MontebrasiteItem());
	public static final RegistryObject<Item> NATROMONTEBRASITE = REGISTRY.register("natromontebrasite", () -> new NatromontebrasiteItem());
	public static final RegistryObject<Item> PERICLASE = REGISTRY.register("periclase", () -> new PericlaseItem());
	public static final RegistryObject<Item> PYROXMANGITE = REGISTRY.register("pyroxmangite", () -> new PyroxmangiteItem());
	public static final RegistryObject<Item> SARCOLITE = REGISTRY.register("sarcolite", () -> new SarcoliteItem());
	public static final RegistryObject<Item> SCORZALITE = REGISTRY.register("scorzalite", () -> new ScorzaliteItem());
	public static final RegistryObject<Item> SCAPOLITE = REGISTRY.register("scapolite", () -> new ScapoliteItem());
	public static final RegistryObject<Item> SODALITE = REGISTRY.register("sodalite", () -> new SodaliteItem());
	public static final RegistryObject<Item> TUGTUPITE = REGISTRY.register("tugtupite", () -> new TugtupiteItem());
	public static final RegistryObject<Item> BRAZILIANITE = REGISTRY.register("brazilianite", () -> new BrazilianiteItem());
	public static final RegistryObject<Item> BREITHAUPTITE = REGISTRY.register("breithauptite", () -> new BreithauptiteItem());
	public static final RegistryObject<Item> CHROMITE = REGISTRY.register("chromite", () -> new ChromiteItem());
	public static final RegistryObject<Item> ENSTATITE = REGISTRY.register("enstatite", () -> new EnstatiteItem());
	public static final RegistryObject<Item> LINOBATE = REGISTRY.register("linobate", () -> new LinobateItem());
	public static final RegistryObject<Item> MAGNESIOCHROMITE = REGISTRY.register("magnesiochromite", () -> new MagnesiochromiteItem());
	public static final RegistryObject<Item> MOLDAVITE = REGISTRY.register("moldavite", () -> new MoldaviteItem());
	public static final RegistryObject<Item> WILLEMITE = REGISTRY.register("willemite", () -> new WillemiteItem());
	public static final RegistryObject<Item> AESCHYNITE = REGISTRY.register("aeschynite", () -> new AeschyniteItem());
	public static final RegistryObject<Item> BRONZITE = REGISTRY.register("bronzite", () -> new BronziteItem());
	public static final RegistryObject<Item> CANCRINITE = REGISTRY.register("cancrinite", () -> new CancriniteItem());
	public static final RegistryObject<Item> CATAPLEIITE = REGISTRY.register("catapleiite", () -> new CatapleiiteItem());
	public static final RegistryObject<Item> CLINOENSTATITE = REGISTRY.register("clinoenstatite", () -> new ClinoenstatiteItem());
	public static final RegistryObject<Item> DAVIDITE = REGISTRY.register("davidite", () -> new DaviditeItem());
	public static final RegistryObject<Item> DIOPSIDE = REGISTRY.register("diopside", () -> new DiopsideItem());
	public static final RegistryObject<Item> FERROSILITE = REGISTRY.register("ferrosilite", () -> new FerrosiliteItem());
	public static final RegistryObject<Item> HORNBLENDE = REGISTRY.register("hornblende", () -> new HornblendeItem());
	public static final RegistryObject<Item> SULPHUR = REGISTRY.register("sulphur", () -> new SulphurItem());
	public static final RegistryObject<Item> COVELLITE = REGISTRY.register("covellite", () -> new CovelliteItem());
	public static final RegistryObject<Item> MELONITE = REGISTRY.register("melonite", () -> new MeloniteItem());
	public static final RegistryObject<Item> REALGAR = REGISTRY.register("realgar", () -> new RealgarItem());
	public static final RegistryObject<Item> VIVIANITE = REGISTRY.register("vivianite", () -> new VivianiteItem());
	public static final RegistryObject<Item> PALYGORSKITE = REGISTRY.register("palygorskite", () -> new PalygorskiteItem());
	public static final RegistryObject<Item> PYROPHYLLITE = REGISTRY.register("pyrophyllite", () -> new PyrophylliteItem());
	public static final RegistryObject<Item> TALC = REGISTRY.register("talc", () -> new TalcItem());
	public static final RegistryObject<Item> H = REGISTRY.register("h", () -> new HItem());
	public static final RegistryObject<Item> LI = REGISTRY.register("li", () -> new LiItem());
	public static final RegistryObject<Item> BE = REGISTRY.register("be", () -> new BeItem());
	public static final RegistryObject<Item> B = REGISTRY.register("b", () -> new BItem());
	public static final RegistryObject<Item> C = REGISTRY.register("c", () -> new CItem());
	public static final RegistryObject<Item> N = REGISTRY.register("n", () -> new NItem());
	public static final RegistryObject<Item> O = REGISTRY.register("o", () -> new OItem());
	public static final RegistryObject<Item> F = REGISTRY.register("f", () -> new FItem());
	public static final RegistryObject<Item> NE = REGISTRY.register("ne", () -> new NeItem());
	public static final RegistryObject<Item> NA = REGISTRY.register("na", () -> new NaItem());
	public static final RegistryObject<Item> MG = REGISTRY.register("mg", () -> new MgItem());
	public static final RegistryObject<Item> AL = REGISTRY.register("al", () -> new AlItem());
	public static final RegistryObject<Item> SI = REGISTRY.register("si", () -> new SiItem());
	public static final RegistryObject<Item> P = REGISTRY.register("p", () -> new PItem());
	public static final RegistryObject<Item> S = REGISTRY.register("s", () -> new SItem());
	public static final RegistryObject<Item> CL = REGISTRY.register("cl", () -> new ClItem());
	public static final RegistryObject<Item> AR = REGISTRY.register("ar", () -> new ArItem());
	public static final RegistryObject<Item> K = REGISTRY.register("k", () -> new KItem());
	public static final RegistryObject<Item> CA = REGISTRY.register("ca", () -> new CaItem());
	public static final RegistryObject<Item> SC = REGISTRY.register("sc", () -> new ScItem());
	public static final RegistryObject<Item> TI = REGISTRY.register("ti", () -> new TiItem());
	public static final RegistryObject<Item> CR = REGISTRY.register("cr", () -> new CrItem());
	public static final RegistryObject<Item> MN = REGISTRY.register("mn", () -> new MnItem());
	public static final RegistryObject<Item> FE = REGISTRY.register("fe", () -> new FeItem());
	public static final RegistryObject<Item> CO = REGISTRY.register("co", () -> new CoItem());
	public static final RegistryObject<Item> NI = REGISTRY.register("ni", () -> new NiItem());
	public static final RegistryObject<Item> CU = REGISTRY.register("cu", () -> new CuItem());
	public static final RegistryObject<Item> ZN = REGISTRY.register("zn", () -> new ZnItem());
	public static final RegistryObject<Item> GA = REGISTRY.register("ga", () -> new GaItem());
	public static final RegistryObject<Item> AS = REGISTRY.register("as", () -> new AsItem());
	public static final RegistryObject<Item> GE = REGISTRY.register("ge", () -> new GeItem());
	public static final RegistryObject<Item> SE = REGISTRY.register("se", () -> new SeItem());
	public static final RegistryObject<Item> BR = REGISTRY.register("br", () -> new BrItem());
	public static final RegistryObject<Item> KR = REGISTRY.register("kr", () -> new KrItem());
	public static final RegistryObject<Item> RB = REGISTRY.register("rb", () -> new RbItem());
	public static final RegistryObject<Item> SR = REGISTRY.register("sr", () -> new SrItem());
	public static final RegistryObject<Item> Y = REGISTRY.register("y", () -> new YItem());
	public static final RegistryObject<Item> ZR = REGISTRY.register("zr", () -> new ZrItem());
	public static final RegistryObject<Item> NB = REGISTRY.register("nb", () -> new NbItem());
	public static final RegistryObject<Item> MO = REGISTRY.register("mo", () -> new MoItem());
	public static final RegistryObject<Item> TC = REGISTRY.register("tc", () -> new TcItem());
	public static final RegistryObject<Item> RU = REGISTRY.register("ru", () -> new RuItem());
	public static final RegistryObject<Item> PD = REGISTRY.register("pd", () -> new PdItem());
	public static final RegistryObject<Item> AG = REGISTRY.register("ag", () -> new AgItem());
	public static final RegistryObject<Item> CD = REGISTRY.register("cd", () -> new CdItem());
	public static final RegistryObject<Item> IN = REGISTRY.register("in", () -> new InItem());
	public static final RegistryObject<Item> SN = REGISTRY.register("sn", () -> new SnItem());
	public static final RegistryObject<Item> SB = REGISTRY.register("sb", () -> new SbItem());
	public static final RegistryObject<Item> TE = REGISTRY.register("te", () -> new TeItem());
	public static final RegistryObject<Item> I = REGISTRY.register("i", () -> new IItem());
	public static final RegistryObject<Item> XE = REGISTRY.register("xe", () -> new XeItem());
	public static final RegistryObject<Item> CS = REGISTRY.register("cs", () -> new CsItem());
	public static final RegistryObject<Item> BA = REGISTRY.register("ba", () -> new BaItem());
	public static final RegistryObject<Item> LA = REGISTRY.register("la", () -> new LaItem());
	public static final RegistryObject<Item> HF = REGISTRY.register("hf", () -> new HfItem());
	public static final RegistryObject<Item> TA = REGISTRY.register("ta", () -> new TaItem());
	public static final RegistryObject<Item> W = REGISTRY.register("w", () -> new WItem());
	public static final RegistryObject<Item> RE = REGISTRY.register("re", () -> new ReItem());
	public static final RegistryObject<Item> OS = REGISTRY.register("os", () -> new OsItem());
	public static final RegistryObject<Item> PT = REGISTRY.register("pt", () -> new PtItem());
	public static final RegistryObject<Item> IR = REGISTRY.register("ir", () -> new IrItem());
	public static final RegistryObject<Item> AU = REGISTRY.register("au", () -> new AuItem());
	public static final RegistryObject<Item> HG = REGISTRY.register("hg", () -> new HgItem());
	public static final RegistryObject<Item> TL = REGISTRY.register("tl", () -> new TlItem());
	public static final RegistryObject<Item> PB = REGISTRY.register("pb", () -> new PbItem());
	public static final RegistryObject<Item> BI = REGISTRY.register("bi", () -> new BiItem());
	public static final RegistryObject<Item> PO = REGISTRY.register("po", () -> new PoItem());
	public static final RegistryObject<Item> AT = REGISTRY.register("at", () -> new AtItem());
	public static final RegistryObject<Item> RN = REGISTRY.register("rn", () -> new RnItem());
	public static final RegistryObject<Item> FR = REGISTRY.register("fr", () -> new FrItem());
	public static final RegistryObject<Item> RA = REGISTRY.register("ra", () -> new RaItem());
	public static final RegistryObject<Item> AC = REGISTRY.register("ac", () -> new AcItem());
	public static final RegistryObject<Item> RF = REGISTRY.register("rf", () -> new RfItem());
	public static final RegistryObject<Item> DB = REGISTRY.register("db", () -> new DbItem());
	public static final RegistryObject<Item> BH = REGISTRY.register("bh", () -> new BhItem());
	public static final RegistryObject<Item> HS = REGISTRY.register("hs", () -> new HsItem());
	public static final RegistryObject<Item> CE = REGISTRY.register("ce", () -> new CeItem());
	public static final RegistryObject<Item> PR = REGISTRY.register("pr", () -> new PrItem());
	public static final RegistryObject<Item> ND = REGISTRY.register("nd", () -> new NdItem());
	public static final RegistryObject<Item> PM = REGISTRY.register("pm", () -> new PmItem());
	public static final RegistryObject<Item> SM = REGISTRY.register("sm", () -> new SmItem());
	public static final RegistryObject<Item> EU = REGISTRY.register("eu", () -> new EuItem());
	public static final RegistryObject<Item> GD = REGISTRY.register("gd", () -> new GdItem());
	public static final RegistryObject<Item> TB = REGISTRY.register("tb", () -> new TbItem());
	public static final RegistryObject<Item> DY = REGISTRY.register("dy", () -> new DyItem());
	public static final RegistryObject<Item> HO = REGISTRY.register("ho", () -> new HoItem());
	public static final RegistryObject<Item> ER = REGISTRY.register("er", () -> new ErItem());
	public static final RegistryObject<Item> TM = REGISTRY.register("tm", () -> new TmItem());
	public static final RegistryObject<Item> YB = REGISTRY.register("yb", () -> new YbItem());
	public static final RegistryObject<Item> TH = REGISTRY.register("th", () -> new ThItem());
	public static final RegistryObject<Item> LU = REGISTRY.register("lu", () -> new LuItem());
	public static final RegistryObject<Item> PA = REGISTRY.register("pa", () -> new PaItem());
	public static final RegistryObject<Item> U = REGISTRY.register("u", () -> new UItem());
	public static final RegistryObject<Item> NP = REGISTRY.register("np", () -> new NpItem());
	public static final RegistryObject<Item> PU = REGISTRY.register("pu", () -> new PuItem());
	public static final RegistryObject<Item> AM = REGISTRY.register("am", () -> new AmItem());
	public static final RegistryObject<Item> CM = REGISTRY.register("cm", () -> new CmItem());
	public static final RegistryObject<Item> ES = REGISTRY.register("es", () -> new EsItem());
	public static final RegistryObject<Item> MD = REGISTRY.register("md", () -> new MdItem());
	public static final RegistryObject<Item> FM = REGISTRY.register("fm", () -> new FmItem());
	public static final RegistryObject<Item> NO = REGISTRY.register("no", () -> new NoItem());
	public static final RegistryObject<Item> LR = REGISTRY.register("lr", () -> new LrItem());
	public static final RegistryObject<Item> MT = REGISTRY.register("mt", () -> new MtItem());
	public static final RegistryObject<Item> DS = REGISTRY.register("ds", () -> new DsItem());
	public static final RegistryObject<Item> RG = REGISTRY.register("rg", () -> new RgItem());
	public static final RegistryObject<Item> CN = REGISTRY.register("cn", () -> new CnItem());
	public static final RegistryObject<Item> NH = REGISTRY.register("nh", () -> new NhItem());
	public static final RegistryObject<Item> FL = REGISTRY.register("fl", () -> new FlItem());
	public static final RegistryObject<Item> MC = REGISTRY.register("mc", () -> new McItem());
	public static final RegistryObject<Item> LV = REGISTRY.register("lv", () -> new LvItem());
	public static final RegistryObject<Item> TS = REGISTRY.register("ts", () -> new TsItem());
	public static final RegistryObject<Item> OG = REGISTRY.register("og", () -> new OgItem());
	public static final RegistryObject<Item> CF = REGISTRY.register("cf", () -> new CfItem());
	public static final RegistryObject<Item> RH = REGISTRY.register("rh", () -> new RhItem());
	public static final RegistryObject<Item> SG = REGISTRY.register("sg", () -> new SgItem());
	public static final RegistryObject<Item> V = REGISTRY.register("v", () -> new VItem());
	public static final RegistryObject<Item> ADAKITE = block(LifealikesModBlocks.ADAKITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> VERTISOL = block(LifealikesModBlocks.VERTISOL, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> ANDISOL = block(LifealikesModBlocks.ANDISOL, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> HISTOSOL = block(LifealikesModBlocks.HISTOSOL, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> GLEYSOL = block(LifealikesModBlocks.GLEYSOL, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> ARIDISOLS = block(LifealikesModBlocks.ARIDISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> MOLLISOLS = block(LifealikesModBlocks.MOLLISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> ALFISOLS = block(LifealikesModBlocks.ALFISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SPODOSOLS = block(LifealikesModBlocks.SPODOSOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> INCEPTISOLS = block(LifealikesModBlocks.INCEPTISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> ENTISOLS = block(LifealikesModBlocks.ENTISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> OXISOLS = block(LifealikesModBlocks.OXISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> ULTISOLS = block(LifealikesModBlocks.ULTISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> GELISOLS = block(LifealikesModBlocks.GELISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PODOSOLS = block(LifealikesModBlocks.PODOSOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> LUVISOLS = block(LifealikesModBlocks.LUVISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> CHERNOZEMS = block(LifealikesModBlocks.CHERNOZEMS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> FERRALSOLS = block(LifealikesModBlocks.FERRALSOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> NITISOLS = block(LifealikesModBlocks.NITISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> LEPTOSOLS = block(LifealikesModBlocks.LEPTOSOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> REGOSOLS = block(LifealikesModBlocks.REGOSOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> CALCISOLS = block(LifealikesModBlocks.CALCISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> LITHOSOLS = block(LifealikesModBlocks.LITHOSOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PLINTHOSOLS = block(LifealikesModBlocks.PLINTHOSOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PLANOSOLS = block(LifealikesModBlocks.PLANOSOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> CAMBISOLS = block(LifealikesModBlocks.CAMBISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SOLONCHAKS = block(LifealikesModBlocks.SOLONCHAKS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SOLONETZ = block(LifealikesModBlocks.SOLONETZ, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> MUGEARITE = block(LifealikesModBlocks.MUGEARITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SHOSHONITE = block(LifealikesModBlocks.SHOSHONITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> BASANITE = block(LifealikesModBlocks.BASANITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> BLAIRMORITE = block(LifealikesModBlocks.BLAIRMORITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> BONINITE = block(LifealikesModBlocks.BONINITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> CARBONATITE = block(LifealikesModBlocks.CARBONATITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> CHARNOCKITE = block(LifealikesModBlocks.CHARNOCKITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> ENDERBITE = block(LifealikesModBlocks.ENDERBITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> DACITE = block(LifealikesModBlocks.DACITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> DIABASE = block(LifealikesModBlocks.DIABASE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> DIORITE = block(LifealikesModBlocks.DIORITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> NAPOLEONITE = block(LifealikesModBlocks.NAPOLEONITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> DUNITE = block(LifealikesModBlocks.DUNITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> ESSEXITE = block(LifealikesModBlocks.ESSEXITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> FOIDOLITE = block(LifealikesModBlocks.FOIDOLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> GABBRO = block(LifealikesModBlocks.GABBRO, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> GRANODIORITE = block(LifealikesModBlocks.GRANODIORITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> GRANOPHYRE = block(LifealikesModBlocks.GRANOPHYRE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> HARZBURGITE = block(LifealikesModBlocks.HARZBURGITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> HORNBLENDITE = block(LifealikesModBlocks.HORNBLENDITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> HYALOCLASTITE = block(LifealikesModBlocks.HYALOCLASTITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> ICELANDITE = block(LifealikesModBlocks.ICELANDITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> IGNIMBRITE = block(LifealikesModBlocks.IGNIMBRITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> IJOLITE = block(LifealikesModBlocks.IJOLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> KIMBERLITE = block(LifealikesModBlocks.KIMBERLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> KOMATIITE = block(LifealikesModBlocks.KOMATIITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> LAMPROITE = block(LifealikesModBlocks.LAMPROITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> LAMPROPHYRE = block(LifealikesModBlocks.LAMPROPHYRE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> LATITE = block(LifealikesModBlocks.LATITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> LHERZOLITE = block(LifealikesModBlocks.LHERZOLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> MONZOGRANITE = block(LifealikesModBlocks.MONZOGRANITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> MONZONITE = block(LifealikesModBlocks.MONZONITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> NEPHELINITE = block(LifealikesModBlocks.NEPHELINITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> NORITE = block(LifealikesModBlocks.NORITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PEGMATITE = block(LifealikesModBlocks.PEGMATITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PERIDOTITE = block(LifealikesModBlocks.PERIDOTITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PHONOLITE = block(LifealikesModBlocks.PHONOLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PHONOTEPHRITE = block(LifealikesModBlocks.PHONOTEPHRITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PICRITE = block(LifealikesModBlocks.PICRITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PORPHYRY = block(LifealikesModBlocks.PORPHYRY, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PUMICE = block(LifealikesModBlocks.PUMICE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PYROXENITE = block(LifealikesModBlocks.PYROXENITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> QUARTZOLITE = block(LifealikesModBlocks.QUARTZOLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> RHYODACITE = block(LifealikesModBlocks.RHYODACITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> RHYOLITE = block(LifealikesModBlocks.RHYOLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> COMENDITE = block(LifealikesModBlocks.COMENDITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PANTELLERITE = block(LifealikesModBlocks.PANTELLERITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SCORIA = block(LifealikesModBlocks.SCORIA, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SHONKINITE = block(LifealikesModBlocks.SHONKINITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SOVITE = block(LifealikesModBlocks.SOVITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SYENITE = block(LifealikesModBlocks.SYENITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TACHYLYTE = block(LifealikesModBlocks.TACHYLYTE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TEPHRIPHONOLITE = block(LifealikesModBlocks.TEPHRIPHONOLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TEPHRITE = block(LifealikesModBlocks.TEPHRITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TONALITE = block(LifealikesModBlocks.TONALITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TRACHYANDESITE = block(LifealikesModBlocks.TRACHYANDESITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> BENMOREITE = block(LifealikesModBlocks.BENMOREITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TRACHYBASALT = block(LifealikesModBlocks.TRACHYBASALT, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> HAWAIITE = block(LifealikesModBlocks.HAWAIITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TRACHYTE = block(LifealikesModBlocks.TRACHYTE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TROCTOLITE = block(LifealikesModBlocks.TROCTOLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TRONDHJEMITE = block(LifealikesModBlocks.TRONDHJEMITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TUFF = block(LifealikesModBlocks.TUFF, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> WEBSTERITE = block(LifealikesModBlocks.WEBSTERITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> WEHRLITE = block(LifealikesModBlocks.WEHRLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> ARGILLITE = block(LifealikesModBlocks.ARGILLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> ARKOSE = block(LifealikesModBlocks.ARKOSE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> BRECCIA = block(LifealikesModBlocks.BRECCIA, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> CALCARENITE = block(LifealikesModBlocks.CALCARENITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> CHALK = block(LifealikesModBlocks.CHALK, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> CHERT = block(LifealikesModBlocks.CHERT, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> CLAYSTONE = block(LifealikesModBlocks.CLAYSTONE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> COAL = block(LifealikesModBlocks.COAL, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> CONGLOMERATE = block(LifealikesModBlocks.CONGLOMERATE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> COQUINA = block(LifealikesModBlocks.COQUINA, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> DIAMICTITE = block(LifealikesModBlocks.DIAMICTITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> DIATOMITE = block(LifealikesModBlocks.DIATOMITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> DOLOMITE = block(LifealikesModBlocks.DOLOMITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> EVAPORITE = block(LifealikesModBlocks.EVAPORITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> FLINT = block(LifealikesModBlocks.FLINT, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> GEYSERITE = block(LifealikesModBlocks.GEYSERITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> GREYWACKE = block(LifealikesModBlocks.GREYWACKE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> GRITSTONE = block(LifealikesModBlocks.GRITSTONE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> ITACOLUMITE = block(LifealikesModBlocks.ITACOLUMITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> JASPILLITE = block(LifealikesModBlocks.JASPILLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> LATERITE = block(LifealikesModBlocks.LATERITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> LIGNITE = block(LifealikesModBlocks.LIGNITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> LIMESTONE = block(LifealikesModBlocks.LIMESTONE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> MARL = block(LifealikesModBlocks.MARL, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> MUDSTONE = block(LifealikesModBlocks.MUDSTONE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> OOLITE = block(LifealikesModBlocks.OOLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PHOSPHORITE = block(LifealikesModBlocks.PHOSPHORITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SANDSTONE = block(LifealikesModBlocks.SANDSTONE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SHALE = block(LifealikesModBlocks.SHALE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SILTSTONE = block(LifealikesModBlocks.SILTSTONE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SYLVINITE = block(LifealikesModBlocks.SYLVINITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TILLITE = block(LifealikesModBlocks.TILLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TRAVERTINE = block(LifealikesModBlocks.TRAVERTINE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TUFA = block(LifealikesModBlocks.TUFA, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TURBIDITE = block(LifealikesModBlocks.TURBIDITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> WACKESTONE = block(LifealikesModBlocks.WACKESTONE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> ANTHRACITE = block(LifealikesModBlocks.ANTHRACITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> AMPHIBOLITE = block(LifealikesModBlocks.AMPHIBOLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> BLUESCHIST = block(LifealikesModBlocks.BLUESCHIST, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> CATACLASITE = block(LifealikesModBlocks.CATACLASITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> ECLOGITE = block(LifealikesModBlocks.ECLOGITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> GNEISS = block(LifealikesModBlocks.GNEISS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> GRANULITE = block(LifealikesModBlocks.GRANULITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> GREENSCHIST = block(LifealikesModBlocks.GREENSCHIST, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> HORNFELS = block(LifealikesModBlocks.HORNFELS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> CALCFLINTA = block(LifealikesModBlocks.CALCFLINTA, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> LITCHFIELDITE = block(LifealikesModBlocks.LITCHFIELDITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> MARBLE = block(LifealikesModBlocks.MARBLE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> MIGMATITE = block(LifealikesModBlocks.MIGMATITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> MYLONITE = block(LifealikesModBlocks.MYLONITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> METAPELITE = block(LifealikesModBlocks.METAPELITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> METAPSAMMITE = block(LifealikesModBlocks.METAPSAMMITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PHYLLITE = block(LifealikesModBlocks.PHYLLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PSEUDOTACHYLITE = block(LifealikesModBlocks.PSEUDOTACHYLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> QUARTZITE = block(LifealikesModBlocks.QUARTZITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SCHIST = block(LifealikesModBlocks.SCHIST, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SERPENTINITE = block(LifealikesModBlocks.SERPENTINITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SKARN = block(LifealikesModBlocks.SKARN, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SLATE = block(LifealikesModBlocks.SLATE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SUEVITE = block(LifealikesModBlocks.SUEVITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> SOAPSTONE = block(LifealikesModBlocks.SOAPSTONE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TECTONITE = block(LifealikesModBlocks.TECTONITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> WHITESCHIST = block(LifealikesModBlocks.WHITESCHIST, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> ADAMELLITE = block(LifealikesModBlocks.ADAMELLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> APPINITE = block(LifealikesModBlocks.APPINITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> APHANITE = block(LifealikesModBlocks.APHANITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> BOROLANITE = block(LifealikesModBlocks.BOROLANITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> EPIDOSITE = block(LifealikesModBlocks.EPIDOSITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> FELSITE = block(LifealikesModBlocks.FELSITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> GANISTER = block(LifealikesModBlocks.GANISTER, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> GOSSAN = block(LifealikesModBlocks.GOSSAN, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> JADEITITE = block(LifealikesModBlocks.JADEITITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> JASPEROID = block(LifealikesModBlocks.JASPEROID, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> KENYTE = block(LifealikesModBlocks.KENYTE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> LARVIKITE = block(LifealikesModBlocks.LARVIKITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> LLANITE = block(LifealikesModBlocks.LLANITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> LUXULLIANITE = block(LifealikesModBlocks.LUXULLIANITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> MANGERITE = block(LifealikesModBlocks.MANGERITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> NOVACULITE = block(LifealikesModBlocks.NOVACULITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PIETERSITE = block(LifealikesModBlocks.PIETERSITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PYROLITE = block(LifealikesModBlocks.PYROLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> RODINGITE = block(LifealikesModBlocks.RODINGITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TACONITE = block(LifealikesModBlocks.TACONITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TACHYLITE = block(LifealikesModBlocks.TACHYLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> TESCHENITE = block(LifealikesModBlocks.TESCHENITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> THERALITE = block(LifealikesModBlocks.THERALITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> UNAKITE = block(LifealikesModBlocks.UNAKITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> VARIOLITE = block(LifealikesModBlocks.VARIOLITE, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> WAD = block(LifealikesModBlocks.WAD, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> FLUVISOLS = block(LifealikesModBlocks.FLUVISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> RENDZINAS = block(LifealikesModBlocks.RENDZINAS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> DURISOLS = block(LifealikesModBlocks.DURISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> ARENOSOLS = block(LifealikesModBlocks.ARENOSOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> PELISOLS = block(LifealikesModBlocks.PELISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> STAGNOSOLS = block(LifealikesModBlocks.STAGNOSOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> CRYOSOLS = block(LifealikesModBlocks.CRYOSOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> HISTOSOLS = block(LifealikesModBlocks.HISTOSOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> LIXISOLS = block(LifealikesModBlocks.LIXISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> ALBELUVISOLS = block(LifealikesModBlocks.ALBELUVISOLS, LifealikesModTabs.TAB_TABSTONES);
	public static final RegistryObject<Item> HYPERSTHENE_TEST = REGISTRY.register("hypersthene_test", () -> new HyperstheneTESTItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
